### ISSUE TITLE
VS can't open SPEAK.csproj

### ISSUE THREAD

**Issue by thomasdc** [sobek1985/EntityServiceDemo#1]
What type is the 'SPEAK' project? Visual Studio 2013 can't open it ("Project is incompatible").

Apparently, there aren't any ProjectTypeGuids specified in the .csproj file neither.

Am I missing something here?

**Comment by komainu85** [comment]
The SPEAK project is a TDS project. Do you gave TDS installed? I'll upload a serialization folder later as a fallback

**Comment by thomasdc** [comment]
After installing TDS I indeed managed to open the project.

However, when trying to sync with Sitecore, I get the following error (while syncing '/sitecore/client/MikeRobbins' and it's children):

`Length of field content does not match the content-length attribute. Field name: __Renderings, field id: {F1A1FE9E-A60C-4DDB-A3A0-BB5B29FE732E}`

Any idea?

Another thing I noticed, is that in your packages.config you have a reference to 'Sitecore.Dlls.8.0.141212' and 'Sitecore.Services', both of can't be found on the official Nuget server. Did you create the nupkg's containing the Sitecore dll's yourself and stored them locally?

In general, it looks like a interesting example solution, but in my opinion it needs a 'getting started' guide.

**Comment by komainu85** [comment]
The Sitecore packages are from my own person private nuget repository you should be able to reference in the DLLs from your bin.

Ill add in the serialization folder instead of using TDS later tonight hopefully.

Good idea ill write a get started guide for it/

**Comment by komainu85** [comment]
I've added a getting started guide. I'll add the serialisation folder in the morning to the repo

**Comment by thomasdc** [comment]
Cool, thanks!
